config/routes.rb
Rails.application.routes.draw do
  
  devise_for :podcasts
  root 'welcome#index'
 
  resources :podcasts, only: [:index, :show] do
    resources :episodes
  end

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :podcast
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :episodes 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configuere_permitted_parameters, if: :devise_controller?
  
  protected
  
  def configuere_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :title, :description, :itunes, :stitcher, :podbay) }
  end  
  
  def configuere_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :title, :description, :itunes, :stitcher, :podbay) }
  end

  
  
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :find_podcast
  before_action :find_episode, only: [:show]
  
  
  def new
    @episode = @podcast.episodes.new
  end
  
  def create
    @episode = @podcast.episodes.new episode_params
    if @episode.save
      redirect_to podcast_episode_path(@podcast, @episode)
    else
      render 'new'
    end
  end
  
  def show
    @episodes = Episode.where(podcast_id: @podcast).order("created_at DESC").reject { |e| e.id == @episode.id }
  end
  
  private
  
  def episode_params
    params.require(:episode).permit(:title, :description)
  end
  
  def find_podcast
    @podcast = Podcast.find(params[:podcast_id])
  end
  
  def find_episode
    @episode = Episode.find(params[:id])
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  def index
    @podcasts = Podcast.all.order("created_at DESC")
  end
  
  def show
    @podcast = Podcast.find(params[:id])
    @episodes = Episode.where(podcast_id: @podcast).order("created_at DESC")
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title = '')
    base_title = "PodcastApp" 
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= form_for ([@podcast, @episode]) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
  
  <br>
  <br>
  
  <%= f.label :description %><br>
  <%= f.text_area :description %>
  
  <br>
  <br>
  
  <%= f.submit %>
<% end %>

app/views/episodes/show.html.erb
<!-- Header -->
<%= render 'shared/main_header' %>

<!-- Podcasts showpage -->
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1><%= @podcast.title %></h1>
      <p class="description"><%= @podcast.description %></p>
      <!-- Links -->
      <% unless @podcast.itunes.blank? %>
        <a href="http://www.itunes.com/<%= @podcast.itunes %>" class="subscribe_link">iTunes</a>
      <% end %>  
      <% unless @podcast.stitcher.blank? %>
        <a href="<%= @podcast.stitcher %>" class="subscribe_link">Stitcher</a>
      <% end %>
      <% unless @podcast.podbay.blank? %>
        <a href="<%= @podcast.podbay %>" class="subscribe_link">PodBay</a>
      <% end %>
      <!--/Links -->
    </div>
  </div>
  
  <div id="breadcrumb">
    <%= link_to podcasts_path do %>
      All Podcasts
      <span>/</span>
      <%= link_to @podcast.title, podcast_path(@podcast) %>
      <span>/</span>
      <%= @episode.title %>
    <% end %>
  </div>
  
  <div id="episode_content">
    <div class="wrapper_skinny">
        <img src="/assets/SteveJobs.jpg" alt="User Image" class="current_episode_thumbnail">
        <h2><%= @episode.title %></h2>
        <p class="description"><%= @episode.description %></p>
    </div>
  </div>
  
  <div id="episodes">
    <div class="wrapper_skinny">
      <ul class="cf">
        <%= @episodes.each do |episode| %>
          <li class="cf">
            <div class="episode_thumbnail">
              <a href="#">
                <img src="/assets/SteveJobs.jpg" alt="User Image">
              </a>
            </div>
            <div class="episode_overview">
              <h2><%= link_to episode.title, podcast_episode_path(@podcast, episode) %></h2>
              <p class="description"><%= truncate(episode.description, length: 160) %></p>
            </div>
          </li>
        <% end %>  
      </ul>
    </div>
  </div>
</div>
<!-- /Podcasts showpage -->

<!-- Pagination -->
<%= render 'shared/pagination' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="eng-US" >
  <head>
    <meta charset="UTF-8">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Upload your podcasts for free">
    <meta name="keywords" content="Podcast Application">
    <meta name="author" content="AlvilsK">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'shared/fonts'%>
    <%= render 'shared/shim' %>
  </head>
  <% if notice %> <p class="notice"><%= notice %></p><% end %>
  <% if alert  %><p class="alert"><%= alert %></p><% end %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/show.html.erb
<h1>Episodes#show</h1>
<p>Find me in app/views/episodes/show.html.erb</p>

app/views/podcasts/dashboard.html.erb
<!-- Header -->
<%= render 'shared/main_header' %>

<!-- Podcasts showpage -->
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1>The Rocketship Podcast Dashboard</h1>
    </div>
  </div>
  
  <div id="links">
    <div class="wrapper_skinny">
      <ul>
        <li class="current">Episodes</li>
        <li><a href="#">New Episode</a></li>
        <li><a href="#">Account Settings</a></li>
        <li><a href="#">View Podcast</a></li>
      </ul>
    </div>
  </div>
  
  <div id="episodes">
    <div class="wrapper_skinny">
      <ul class="cf">
        <li class="cf">
          <div class="episode_thumbnail">
            <a href="#">
              <img src="/assets/SteveJobs.jpg" alt="User Image">
            </a>
          </div>
          <div class="episode_overview">
            <h2><a href="#">How to Pull Off 12 (Well Executed) Startups in 12 months</a></h2>
            <p class="description">Aenean laoreet vitae magna nec sodales. Sed in efficitur libero. Sed auctor congue ligula...</p>
            <div class="authorised_links">
              <a href="#">Edit</a>
              <a href="#">Delete</a>
            </div>
          </div>
        </li>
        
        <li class="cf">
          <div class="episode_thumbnail">
            <a href="#">
              <img src="/assets/SteveJobs.jpg" alt="User Image">
            </a>
          </div>
          <div class="episode_overview">
            <h2><a href="#">How to Pull Off 12 (Well Executed) Startups in 12 months</a></h2>
            <p class="description">Aenean laoreet vitae magna nec sodales. Sed in efficitur libero. Sed auctor congue ligula...</p>
            <div class="authorised_links">
              <a href="#">Edit</a>
              <a href="#">Delete</a>
            </div>            
          </div>
        </li>
        
        <li class="cf">
          <div class="episode_thumbnail">
            <a href="#">
              <img src="/assets/SteveJobs.jpg" alt="User Image">
            </a>
          </div>
          <div class="episode_overview">
            <h2><a href="#">How to Pull Off 12 (Well Executed) Startups in 12 months</a></h2>
            <p class="description">Aenean laoreet vitae magna nec sodales. Sed in efficitur libero. Sed auctor congue ligula...</p>
            <div class="authorised_links">
              <a href="#">Edit</a>
              <a href="#">Delete</a>
            </div>          
          </div>
        </li>
        
        <li class="cf">
          <div class="episode_thumbnail">
            <a href="#">
              <img src="/assets/SteveJobs.jpg" alt="User Image">
            </a>
          </div>
          <div class="episode_overview">
            <h2><a href="#">How to Pull Off 12 (Well Executed) Startups in 12 months</a></h2>
            <p class="description">Aenean laoreet vitae magna nec sodales. Sed in efficitur libero. Sed auctor congue ligula...</p>
            <div class="authorised_links">
              <a href="#">Edit</a>
              <a href="#">Delete</a>
            </div>          
          </div>
        </li>        
      </ul>
    </div>
  </div>
</div>
<!-- /Podcasts showpage -->

<!-- Pagination -->
<%= render 'shared/pagination' %>

app/views/podcasts/index.html.erb
<% provide(:title, "Podcasts") %>

<!-- Header -->
<%= render 'shared/main_header' %>

<!-- Banner -->
<div id="banner" class="podcasts_banner">
  <h1>Discover your new favorite podcast</h1>
</div>

<!-- Podcast previews -->
<div id="podcasts" class="cf">
  <div class="wrapper">
    <ul>
      <% @podcasts.each do |podcast| %>
        <%= link_to podcast do %>
          <li>
            <img src="/assets/samplepicture.jpg" alt="Sample Image"> 
            <div class="podcast_overview">
              <h2><%= podcast.title %></h2>
              <p class="episode_count">1 Episode</p>
            </div>
          </li>
        <% end %>
      <% end %>
      
      <a href="#">
        <li>
          <img src="/assets/samplepicture.jpg" alt="Sample Image"> 
          <div class="podcast_overview">
            <h2>Narwhals Podcast</h2>
            <p class="episode_count">1 Episode</p>
          </div>
        </li>
      </a>

      <a href="#">
        <li>
          <img src="/assets/samplepicture.jpg" alt="Sample Image"> 
          <div class="podcast_overview">
            <h2>Narwhals Podcast</h2>
            <p class="episode_count">1 Episode</p>
          </div>
        </li>
      </a>      

      <a href="#">
        <li>
          <img src="/assets/samplepicture.jpg" alt="Sample Image"> 
          <div class="podcast_overview">
            <h2>Narwhals Podcast</h2>
            <p class="episode_count">1 Episode</p>
          </div>
        </li>
      </a>

      <a href="#">
        <li>
          <img src="/assets/samplepicture.jpg" alt="Sample Image"> 
          <div class="podcast_overview">
            <h2>Narwhals Podcast</h2>
            <p class="episode_count">1 Episode</p>
          </div>
        </li>
      </a>

      <a href="#">
        <li>
          <img src="/assets/samplepicture.jpg" alt="Sample Image"> 
          <div class="podcast_overview">
            <h2>Narwhals Podcast</h2>
            <p class="episode_count">1 Episode</p>
          </div>
        </li>
      </a>      
    </ul>
  </div>
</div>
<!-- /Podcasts previews -->

<!-- Pagination -->
<%= render 'shared/pagination'%>

app/views/podcasts/show.html.erb
<!-- Header -->
<%= render 'shared/main_header' %>

<!-- Podcasts showpage -->
<div id="podcast_show">
  <div id="show_banner">
    <div class="wrapper_skinny">
      <h1><%= @podcast.title %></h1>
      <p class="description"><%= @podcast.description %></p>
      <!-- Links -->
      <% unless @podcast.itunes.blank? %>
        <a href="http://www.itunes.com/<%= @podcast.itunes %>" class="subscribe_link">iTunes</a>
      <% end %>  
      <% unless @podcast.stitcher.blank? %>
        <a href="<%= @podcast.stitcher %>" class="subscribe_link">Stitcher</a>
      <% end %>
      <% unless @podcast.podbay.blank? %>
        <a href="<%= @podcast.podbay %>" class="subscribe_link">PodBay</a>
      <% end %>
      <!--/Links -->
    </div>
  </div>
  
  <!-- Breadcrumb -->
  <div id="breadcrumb">
    <%= link_to podcasts_path do %>
      All Podcasts
      <span>/</span>
      The Rocketship Podcast
    <% end %>
  </div>
  
  <div id="episodes">
    <div class="wrapper_skinny">
      <ul class="cf">
        <% @episodes.each do |episode| %>
          <li class="cf">
            <div class="episode_thumbnail">
              <a href="#">
                <img src="/assets/SteveJobs.jpg" alt="User Image">
              </a>
            </div>
            <div class="episode_overview">
              <h2><%= link_to episode.title, podcast_episode_path(@podcast, episode) %></h2>
              <p class="description"><%= truncate(episode.description, length: 160) %></p>
            </div>
          </li>
        <% end %>  
      </ul>
    </div>
  </div>
</div>
<!-- /Podcasts showpage -->

<!-- Pagination -->
<%= render 'shared/pagination' %>

app/views/shared/_fonts.html.erb
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,700italic' rel='stylesheet' type='text/css'>

app/views/shared/_header.html.erb
<div class="wrapper_wide">
	<header id="header" class="cf">
		<%= link_to 'PodcastApp', root_path, id: "logo" %>
		<nav>
			<ul>
				<% if !podcast_signed_in? %>
					<li><%= link_to "Create a Podcast" %></li>
					<li><%= link_to "Explore", podcasts_path %></li>
					<li><%= link_to "Sign in", new_podcast_session_path %></li>
				<% else %>
					<li><%= link_to "Create a Podcast" %></li>
					<li><%= link_to "Explore", podcasts_path %></li>
					<li><%= link_to "Sign out", destroy_podcast_session_path, method: :delete %></li>
				<% end %>
			</ul>
		</nav>
	</header>
</div>

app/views/shared/_main_header.html.erb
<div class="wrapper_wide">
	<header id="main_header" class="cf">
		<%= link_to 'PodcastApp', root_path, id: "logo" %>
		<nav>
			<ul>
			<% if !podcast_signed_in? %>
				<li><%= link_to "Create a Podcast" %></li>
				<li><%= link_to "Explore", podcasts_path %></li>
				<li><%= link_to "Sign in", new_podcast_session_path %></li>
			<% else %>
				<li><%= link_to "Create a Podcast" %></li>
				<li><%= link_to "Explore", podcasts_path %></li>
				<li><%= link_to "Sign out", destroy_podcast_session_path, method: :delete %></li>
			<% end %>
			</ul>
		</nav>
	</header>
</div>

app/views/shared/_pagination.html.erb
<div class="pagination">
  <span class="previous_page disabled">Previous</span>
  <em class="current">1</em>
  <a href="#">2</a>
  <a class="next_page" href="#">Next</a>
</div>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/welcome/index.html.erb
<div id="background">
    <%= render 'shared/header' %>
    <div class="wrapper_wide">
      <% if !podcast_signed_in? %>
      	<h1>Discover your new favorite<br> podcast, or create your own.</h1>
      	<%= link_to "Create a Podcast", new_podcast_registration_path, class: "button button_highlight" %>
        <%= link_to "Explore", podcasts_path, class: "button button_white" %>
      <% else %>
        <h1>Discover your new favorite<br> podcast, or create your own.</h1>
        <%= link_to "Explore", podcasts_path, class: "button button_white" %>
      <% end %>
    </div>
</div>